### PR TITLE
Use pre/post Ceph servicesOverride in uni05epsilon HCI

### PR DESCRIPTION
**Pull request by fultonj**
This patch applies very similar changes as the commit below for the same reasons but to uni05epsilon.

commit 3ebad70fd9488ff2995553e8acc5e4fc85f24f1e

Jira: https://issues.redhat.com/browse/OSPRH-9222

### CODE REVIEW

**Comment by fultonj** [comment]
Simple testing.

```
1. PRE deployment

[fultonj@runcible uni05epsilon{OSPRH-9222}]$ kustomize build edpm-pre-ceph/deployment
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: edpm-deployment-pre-ceph
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm
  servicesOverride:
  - bootstrap
  - download-cache
  - configure-network
  - validate-network
  - install-os
  - ceph-hci-pre
  - configure-os
  - ssh-known-hosts
  - run-os
  - reboot-os
[fultonj@runcible uni05epsilon{OSPRH-9222}]$ 


2. POST deployment

[fultonj@runcible uni05epsilon{OSPRH-9222}]$ kustomize build deployment
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: edpm-deployment-post-ceph
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm
  servicesOverride:
  - install-certs
  - ceph-client
  - ovn
  - neutron-metadata
  - libvirt
  - nova-custom
[fultonj@runcible uni05epsilon{OSPRH-9222}]$ 


4. PRE nodeset

[fultonj@runcible uni05epsilon{OSPRH-9222}]$ kustomize build edpm-pre-ceph/nodeset
...
  services:
  - bootstrap
  - download-cache
  - configure-network
  - validate-network
  - install-os
  - ceph-hci-pre
  - configure-os
  - ssh-known-hosts
  - run-os
  - reboot-os
  - install-certs
  - ceph-client
  - ovn
  - neutron-metadata
  - libvirt
[fultonj@runcible uni05epsilon{OSPRH-9222}]$ 

4. POST nodeset

[fultonj@runcible uni05epsilon{OSPRH-9222}]$ kustomize build
...
  services:
  - bootstrap
  - download-cache
  - configure-network
  - validate-network
  - install-os
  - ceph-hci-pre
  - configure-os
  - ssh-known-hosts
  - run-os
  - reboot-os
  - install-certs
  - ceph-client
  - ovn
  - neutron-metadata
  - libvirt
  - nova-custom
---
[fultonj@runcible uni05epsilon{OSPRH-9222}]$ 
```

**Comment by fultonj** [comment]
Note that it has a slightly different service list than `va/hci`
```
[fultonj@runcible uni05epsilon{main}]$ yq -o=json '.data.nodeset.services' edpm-pre-ceph/nodeset/values.yaml
[
  "bootstrap",
  "download-cache",
  "configure-network",
  "validate-network",
  "install-os",
  "ceph-hci-pre",
  "configure-os",
  "ssh-known-hosts",
  "run-os",
  "reboot-os"
]
[fultonj@runcible uni05epsilon{main}]$ yq -o=json '.data.nodeset.services' values.yaml
[
  "install-certs",
  "ceph-client",
  "ovn",
  "neutron-metadata",
  "libvirt",
  "nova-custom"
]
[fultonj@runcible uni05epsilon{main}]$ 
```

**Comment by fultonj** [comment]
@sdatko fyi

**Comment by sdatko** [comment]
Tested – we are fine to merge (I do not see difference in tests)

**Review by abays — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
