### PR TITLE
Add ovn-encap-tos inherit to delta-ipv6

### PR DESCRIPTION
**Pull request by fyanac**
Related to [OSPRH-6712](https://issues.redhat.com//browse/OSPRH-6712)

### CODE REVIEW

**Comment by fultonj** [comment]
@fyanac has this been tested in uni07eta ?

**Comment by fyanac** [comment]
no yet, I'm testing it

**Comment by fyanac** [comment]
Hi,
I tested the parameter in env and it works

**Review by fultonj — APPROVED** [review]
/approve
/lgtm

**Comment by fultonj** [comment]
@fyanac I'm merging this. If you want it to be tested in 18, then please cherry pick it to

https://github.com/openstack-k8s-operators/architecture/tree/18.0.0-proposed

**Pull request merged**
