### PR TITLE
remove route in nncp

### PR DESCRIPTION
**Pull request by mnietoji**
It is causing issues, it is not possible to connect from any pod, for example tempest pod or openstackclient pod to compute nodes using control plane network (192.168.122.0/24)

Not sure what issue is trying to solve this route, I think it is not needed

### CODE REVIEW

**Comment by fultonj** [comment]
-1 

This is failing the following test
  https://github.com/openstack-k8s-operators/architecture/actions/runs/8647363849/job/23708643221?pr=177

**Comment by fultonj** [comment]
Please run `./test-kustomizations.sh examples/` in your branch and then update until it passes.

**Comment by leifmadsen** [comment]
@mnietoji @karelyatin here is an example PR of a more appropriate way to address this, since removing the configmap values won't work, as they are required by the base components:  https://github.com/openstack-k8s-operators/architecture/pull/203

Do you still feel this PR is necessary? If not, feel free to close it out.

**Comment by karelyatin** [comment]
Closing as per last discussion above

**Pull request closed without merging**
