### PR TITLE
Restructure for DTs and rename VA1 to HCI

### PR DESCRIPTION
**Pull request by fultonj**
Store not only VAs but also DTs in this repo and create a subdirectory for each to keep them separate.

Move `validated_arch_1` to the new `va` subdirectory and rename it `hci`.

Create `dt` subdirectory and include an explanation on how a DT differs from a VA.

### CODE REVIEW

**Comment by fultonj** [comment]
Let's hold until we have agreement. Preview here https://github.com/fultonj/architecture/tree/dt_va_sub

**Review by abays — APPROVED** [review]
/lgtm

**Review by fmount — APPROVED** [review]
+1 from me

**Comment by ASBishop** [comment]
+1 from me as well

**Pull request merged**
