### PR TITLE
Add karelyatin to reviewers list

### PR DESCRIPTION
**Pull request by fultonj**

### CODE REVIEW

**Comment by fultonj** [comment]
Are you ok @karelyatin with being on the reviewer list?

**Comment by fultonj** [comment]
- if any one listed under this https://github.com/openstack-k8s-operators/architecture/blob/main/OWNERS#L1 sends a pr, the pr will be automatically approved
- if contributors sends the pr, then as a approver we need to add /lgtm and /approve comment in the pr to get it merged

Yatin's reviews have been pretty thorough

**Comment by karelyatin** [comment]
/lgtm 

Thanks @fultonj

**Comment by fultonj** [comment]
Just adding @raukadah who enabled zuul gate pipeline in architecture repo yesterday. My understanding is that once lgtm and approved label gate added, rdoproject.org/github-gate will start, zuul will merge the code in the main branch. I think we have both of those in this PR so I want his review to confirm everything is OK with the zuul gate pipeline.

**Review by raukadah — APPROVED** [review]

**Comment by raukadah** [comment]
> Just adding @raukadah who enabled zuul gate pipeline in architecture repo yesterday. My understanding is that once lgtm and approved label gate added, rdoproject.org/github-gate will start, zuul will merge the code in the main branch. I think we have both of those in this PR so I want his review to confirm everything is OK with the zuul gate pipeline.

It had all the required labels. Not sure why it is not working. But I applied approved from github UI. Then It worked. I am checking with zuul team what is going on there.

**Pull request merged**
