### PR TITLE
Multibackend stores DT

### PR DESCRIPTION
**Pull request by maximsava12**
This is draft PR for creating DT

### CODE REVIEW

**Comment by tosky** [comment]
Couldn't this be handled by one of the DTs proposed in https://github.com/openstack-k8s-operators/architecture/pull/45, for example extending uniepsilon?

Also, do tempest tests for glance properly handle different glance backends? Or do they just use a random backend?

**Comment by tosky** [comment]
I see a change to VA1, is that intended? Also, is this still needed or could it be merged into another DT as proposed?

**Comment by maximsava12** [comment]
Yes,the change is intended.Not sure why i see the fix network PR here )). 
The can merge to another DT

**Comment by maximsava12** [comment]
Close it, as this DT implemented in  Uni DT epsilon.
https://github.com/openstack-k8s-operators/architecture/pull/45/commits/184193a7c2c91c6a9a39cd8043c9ad1591ee8432#diff-1abbe2ddd94883298848665c0dfa4994d6509025bfc3441a8d89d1612b0aa065

**Pull request closed without merging**
