### PR TITLE
Add edpmServiceType to nova-custom-sriov srv

### PR DESCRIPTION
**Pull request by jamepark4**
Add  `edpmServiceType: nova` to the nova-custom-sriov service for the sriov architecture scenario.

### CODE REVIEW

**Review by gibizer — APPROVED** [review]
make sense to me

**Comment by abays** [comment]
I know this is targeting the SRIOV-related NFV VAs, but there's another NFV VA2 (for OVS-DPDK only) that seems like it would need the same thing [1].  Just wondering if we should adjust them all at the same time.

[1] https://github.com/openstack-k8s-operators/architecture/blob/main/va/nfv/ovs-dpdk/edpm/nodeset/nova_ovs_dpdk.yaml

**Comment by jamepark4** [comment]
> I know this is targeting the SRIOV-related NFV VAs, but there's another NFV VA2 (for OVS-DPDK only) that seems like it would need the same thing [1]. Just wondering if we should adjust them all at the same time.
> 
> [1] https://github.com/openstack-k8s-operators/architecture/blob/main/va/nfv/ovs-dpdk/edpm/nodeset/nova_ovs_dpdk.yaml

Yup makes sense I'll update that as well.

**Review by abays — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
