### PR TITLE
Refactor to use kustomize with bases

### PR DESCRIPTION
**Pull request by mdbooth**
This primarily:
* Moves and renames stages 1-4
* Defines stages 1-4 as kustomize resources
* Composes stages 1 and 2 as a single 'olm' resource
* Composes stages 3 and 4 as a single 'osp-control-plane' resource

Stages 5 and 6 become edpm-stage1 and edpm-stage2, but they are otherwise unchanged.

Additionally:
* nmstate_deploy and metallb_deploy move out of the former stage1 into 'networking'
* osp-secrets is defined from a plaintext envfile

Otherwise it makes no functional changes.

### CODE REVIEW

**Comment by SeanMooney** [comment]
this is more or less impossibel to review on github but ill see if i can find time to pull this down and review in vscode

**Comment by fao89** [comment]
I see some WIP commits, is it ready for review?

**Review by fao89 — COMMENTED** [review]
all READMEs need update to mention kustomize

**Review by fultonj — COMMENTED** [review]
@mdbooth thank you for starting this. It has a lot of potential. 

1. Could the READMEs be updated?

It's not yet 100% clear how this replaces what we had if we merged this today. I'm reverse engineering it to figure out how we'd replace stage1 readme and similar.

https://github.com/openstack-k8s-operators/architecture/blob/main/va/hci/stage1/README.md

I'll dumb down my use of kustomize to drive home what needs to be clear to the user if this merges:
```
cd architecture/validated_arch_1/olm
kustomize build > stage1_stage2.yaml
oc apply -f stage1_stage2.yaml
```
I realize you want to rename stage1/2 with OLM and that `oc apply -k` could be used, but I'm trying to make reviewing this easier by connecting this proposal to how this repo works today. Could every readme affected by this patch be updated accordingly?

2. How would the rest of the stages work?

I have more questions since I'm not sure I fully understand how this is supposed to work.

It seems I can get what looks like stage3/4 this way:
```
cd architecture/validated_arch_1/default
kustomize build > stage3_stage4.yaml
oc apply -f stage3_stage4.yaml
```
Would default be re-named osp-control-plane but it's not done yet or is the plan to have the readme tell the user to use default?

Adding kustomizations to edpm-stage1 (formerly stage5) and edpm-stage2 (formerly stage6) is not in scope of this PR intentionally and they should still be applied directly as they today. Is that right?

3. Are these errors expected?

```
[fultonj@jove osp-control-plane{kustomize}]$ kustomize build
Error: nothing selected by ConfigMap.[noVer].[noGrp]/network-values.[noNs]:data.internalapi.endpoint_annotations
[fultonj@jove osp-control-plane{kustomize}]$ ll
total 32
-rw-r--r--  1 fultonj  staff   452B Dec  3 10:27 README.md
-rw-r--r--  1 fultonj  staff   3.5K Dec  3 10:27 kustomization.yaml
-rw-r--r--  1 fultonj  staff   3.7K Dec  3 10:27 openstackcontrolplane.yaml
-rw-r--r--  1 fultonj  staff   954B Dec  3 10:27 osp-secrets.env
[fultonj@jove osp-control-plane{kustomize}]$ pwd
/Users/fultonj/git/ng/architecture/validated_arch_1/bases/osp-control-plane
[fultonj@jove osp-control-plane{kustomize}]$ 
```

```
[fultonj@jove networking{kustomize}]$ kustomize build
Error: nothing selected by ConfigMap.[noVer].[noGrp]/network-values.[noNs]:data.internalapi.iface
[fultonj@jove networking{kustomize}]$ ll
total 80
-rw-r--r--  1 fultonj  staff   796B Dec  3 10:27 README.md
-rw-r--r--  1 fultonj  staff   8.3K Dec  3 10:27 kustomization.yaml
-rw-r--r--  1 fultonj  staff   178B Dec  3 10:27 metallb_deploy.yaml
-rw-r--r--  1 fultonj  staff   655B Dec  3 10:27 metallb_ipaddresspools.yaml
-rw-r--r--  1 fultonj  staff   792B Dec  3 10:27 metallb_l2advertisement.yaml
-rw-r--r--  1 fultonj  staff    66B Dec  3 10:27 nmstate_deploy.yaml
-rw-r--r--  1 fultonj  staff   1.8K Dec  3 10:27 ocp_node_template.yaml
-rw-r--r--  1 fultonj  staff   411B Dec  3 10:27 ocp_nodes_nncp.yaml
[fultonj@jove networking{kustomize}]$ pwd
/Users/fultonj/git/ng/architecture/validated_arch_1/bases/networking
[fultonj@jove networking{kustomize}]$ 
```
I'm going to experiment with this more and see if I can use it to reproduce a standard deployment. If you can comment on the above it would help me do that.

**Comment by fultonj** [comment]
Summarizing my chat with Matt on slack in terms of answering my own questions here.

> 1. Could the READMEs be updated?

Not in this PR. It was meant to provide an example from which to create derivative works but isn't supposed to merge.

> 2. How would the rest of the stages work?
> 
> I have more questions since I'm not sure I fully understand how this is supposed to work.
> 
> It seems I can get what looks like stage3/4 this way:
> 
> ```
> cd architecture/validated_arch_1/default
> kustomize build > stage3_stage4.yaml
> oc apply -f stage3_stage4.yaml
> ```
> 
> Would default be re-named osp-control-plane but it's not done yet or is the plan to have the readme tell the user to use default?
> 
> Adding kustomizations to edpm-stage1 (formerly stage5) and edpm-stage2 (formerly stage6) is not in scope of this PR intentionally and they should still be applied directly as they today. Is that right?

Every directory with a kustomization.yaml can be built, but some of them are for internal use and not intended to be built. There are 2 stages: `olm`, which creates all the olm resources, and `default`, which does everything else. And edpm, which I didn't touch. OLM needs to come first because it loads CRDs. That's the only ordering constraint.

> 3. Are these errors expected?
> ```
> [fultonj@jove osp-control-plane{kustomize}]$ kustomize build
> Error: nothing selected by ConfigMap.[noVer].[noGrp]/network-values.[noNs]:data.internalapi.endpoint_annotations
> [fultonj@jove osp-control-plane{kustomize}]$ ll
> total 32
> -rw-r--r--  1 fultonj  staff   452B Dec  3 10:27 README.md
> -rw-r--r--  1 fultonj  staff   3.5K Dec  3 10:27 kustomization.yaml
> -rw-r--r--  1 fultonj  staff   3.7K Dec  3 10:27 openstackcontrolplane.yaml
> -rw-r--r--  1 fultonj  staff   954B Dec  3 10:27 osp-secrets.env
> [fultonj@jove osp-control-plane{kustomize}]$ pwd
> /Users/fultonj/git/ng/architecture/validated_arch_1/bases/osp-control-plane
> [fultonj@jove osp-control-plane{kustomize}]$ 
> ```

Yes, That's a component, not a Kustomization. You can't build it.

https://github.com/shiftstack/architecture/blob/6eee14cc76459af632e98b0f8cab128883ddb517/validated_arch_1/bases/networking/kustomization.yaml#L1-L2

The reason for doing this is that a Component is evaluated in the context of a resource which includes it.
That means it doesn't have to include values itself, so values can be substituted.
If it was a resource then it would have to contain values, so you wouldn't be able to reuse the substitution logic.

**Comment by fultonj** [comment]
superseded by https://github.com/openstack-k8s-operators/architecture/pull/39

**Pull request closed without merging**
