### PR TITLE
LACP, balance-tcp and IGMP configs changes

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to provide configs for LACP,
balance-tcp and IGMP network template on
compute nodes.

### CODE REVIEW

**Comment by fultonj** [comment]
@Jaganathancse I assume you'll let us know when this is ready for review by removing WIP in the title and getting initial CI green.

**Comment by Jaganathancse** [comment]
> @Jaganathancse I assume you'll let us know when this is ready for review by removing WIP in the title and getting initial CI green.

@fultonj ack

**Comment by fultonj** [comment]
Is this still needed?

**Comment by Jaganathancse** [comment]
> Is this still needed?

yes

**Comment by fultonj** [comment]
Has this been tested and is it ready to merge?

**Pull request merged**
