### PR TITLE
increased NFV timeout

### PR DESCRIPTION
**Pull request by eshulman2**
imcreased nodeset and deployment timeout for NFV jobs due to repeating failures with wait command reaching its timeout

### CODE REVIEW

**Comment by cjeanner** [comment]
/lgtm
Won't change the run time if it ends earlier than the set timeout, but would also avoid to re-kick the job when it times out with the previous values.

**Review by pojadhav — COMMENTED** [review]
LGTM

**Review by abays — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
