### PR TITLE
Drop default.yaml file

### PR DESCRIPTION
**Pull request by raukadah**
openstack-k8s-operators/architecture#375 splits the default vars into different scenario files. https://github.com/openstack-k8s-operators/ci-framework/pull/2267 suggests to use Use cifmw_architecture_scenario to set proper automation file.

So we are no longer needing default.yaml file.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2292

### CODE REVIEW

**Comment by cjeanner** [comment]
/lgtm

There's still the bgp.yaml to split, done via #375 and then we should be good to get the updated yamale + name consistency check (#379) in!

**Comment by cjeanner** [comment]
/hold

let's get tests done.

**Review by cjeanner — APPROVED** [review]

**Comment by cjeanner** [comment]
/override unit
There seems to be some issue with Prow. This check isn't relevant for this specific PR.

**Comment by cjeanner** [comment]
/override ci/prow/unit
There seems to be some issue with Prow. This check isn't relevant for this specific PR.

**Comment by raukadah** [comment]
recheck

**Pull request merged**
