### PR TITLE
Adding baremetalset root password changes

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to add baremetalset root password secret for compute nodes to debug via virtual console.

### CODE REVIEW

**Comment by abays** [comment]
The HCI VA example needs to be updated as well or you get this error:

```
$ kustomize build edpm-pre-ceph > dataplane-pre-ceph.yaml
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/home/ocp/podified/Jaganathancse-architecture/va/hci/edpm-pre-ceph': accumulating components: accumulateDirectory: \"recursed accumulation of path '/home/ocp/podified/Jaganathancse-architecture/lib/dataplane': fieldPath `data.root_password` is missing for replacement source ConfigMap.[noVer].[noGrp]/edpm-values.[noNs]\""
```

**Comment by abays** [comment]
Actually, sorry, I think it would be better to actually have the kustomization in the `va/nfv/*/` directories instead of the `lib` directory.  The reason for this is that the NFV VAs are using baremetal provisioning, whereas the HCI VA is using preprovisioned.  The baremetal secret only applies to baremetal provisioning, so generating it for the HCI VA doesn't make sense.  So maybe we should undo what I suggested earlier and move the logic out of `lib/dataplane/` and into each `va/nfv/*/` directory.

@fultonj thoughts?

**Review by fultonj — APPROVED** [review]
So we're going back to patch set 2?

**Comment by abays** [comment]
> So we're going back to patch set 2?

We would be moving the logic out of `lib/dataplane` and into the middle-tier of `va/nfv/*/` so that the baremetal password is properly applied to only the VAs that currently use baremetal provisioning.

**Comment by fultonj** [comment]
> Actually, sorry, I think it would be better to actually have the kustomization in the `va/nfv/*/` directories instead of the `lib` directory. The reason for this is that the NFV VAs are using baremetal provisioning, whereas the HCI VA is using preprovisioned. 

Yes, HCI is using pre-provisioned. In theory someone could use baremetal provisioned for HCI too. However, because we are being prescriptive here, I agree with the above.

> The baremetal secret only applies to baremetal provisioning, so generating it for the HCI VA doesn't make sense. 

agreed.

> So maybe we should undo what I suggested earlier and move the logic out of `lib/dataplane/` and into each `va/nfv/*/` directory.
> 
> @fultonj thoughts?

yes.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
