### PR TITLE
Tempest config issue fix

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to fix the tempest config issue.

### CODE REVIEW

**Comment by mnietoji** [comment]
It is ok now

**Comment by abays** [comment]
> It is ok now

Do you mean this PR fixes the problem or that the PR is not needed?

**Comment by Jaganathancse** [comment]
> > It is ok now
> 
> Do you mean this PR fixes the problem or that the PR is not needed?

PR needed to fix it.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
