### PR TITLE
Enable Heat for uni04delta-ipv6 DT

### PR DESCRIPTION
**Pull request by gmarcian**
It was a cherry-picked from https://github.com/openstack-k8s-operators/architecture/pull/411

### CODE REVIEW

**Comment by abays** [comment]
Has this been tried in a testproject job?

**Comment by gmarcian** [comment]
@abays It's being tested here: https://gitlab.cee.redhat.com/ci-framework/ci-framework-testproject/-/merge_requests/698

**Comment by abays** [comment]
> @abays It's being tested here: https://gitlab.cee.redhat.com/ci-framework/ci-framework-testproject/-/merge_requests/698

Awesome.  Once that succeeds I think we can merge.

**Comment by gmarcian** [comment]
Testproject job passed: https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/1f6e547f14a44b5495fec56d4ba65785

**Comment by abays** [comment]
> Testproject job passed: https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/1f6e547f14a44b5495fec56d4ba65785

/lgtm
/approve

**Pull request merged**
