### PR TITLE
Neutron API policies integration tempest changes

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to provide option to configure neutron API policies to run tempest on environment.

### CODE REVIEW

**Comment by Jaganathancse** [comment]
recheck

**Review by fultonj — COMMENTED** [review]
This change looks good to me.

The `test-kustomize` workflow (from https://github.com/openstack-k8s-operators/architecture/pull/175) didn't run though because I think it needs a rebase (the test-kustomizations.sh file isn't there otherwise).

I rebased a copy of it on main and it passed. Want to just rebase this PR so we can see a green run of both workflows before we merge?

```
[fultonj@runcible architecture{neutron_policies_tempest_changes}]$ ls
automation  docs  examples  lib  mkdocs.yml  README.md  va
[fultonj@runcible architecture{neutron_policies_tempest_changes}]$ git rebase -i main
Successfully rebased and updated refs/heads/neutron_policies_tempest_changes.
[fultonj@runcible architecture{neutron_policies_tempest_changes}]$ ls
automation  docs  examples  lib  mkdocs.yml  README.md  test-kustomizations.sh  va
[fultonj@runcible architecture{neutron_policies_tempest_changes}]$ ./test-kustomizations.sh examples/
examples/common/metallb/kustomization.yaml: OK
examples/common/nmstate/kustomization.yaml: OK
examples/common/olm/kustomization.yaml: OK
examples/dt/one/kustomization.yaml: OK
examples/va/hci/control-plane/kustomization.yaml: OK
examples/va/hci/control-plane/nncp/kustomization.yaml: OK
examples/va/hci/edpm-pre-ceph/kustomization.yaml: OK
examples/va/hci/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk-sriov/edpm/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk-sriov/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk-sriov/nncp/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk/edpm/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk/kustomization.yaml: OK
examples/va/nfv/ovs-dpdk/nncp/kustomization.yaml: OK
examples/va/nfv/sriov/edpm/kustomization.yaml: OK
examples/va/nfv/sriov/kustomization.yaml: OK
examples/va/nfv/sriov/nncp/kustomization.yaml: OK

:: Summary
No errors!
[fultonj@runcible architecture{neutron_policies_tempest_changes}]$ 
```

**Comment by abays** [comment]
Yes, let's rebase and see the workflows pass.  If so, it looks good to me.

**Comment by Jaganathancse** [comment]
> Yes, let's rebase and see the workflows pass. If so, it looks good to me.

done

**Pull request merged**
