### PR TITLE
EDPM Compute with provision changes

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to support EDPM Compute with provision changes.

### CODE REVIEW

**Review by fultonj — COMMENTED** [review]
I've done all my testing with preprovisioned EDPM nodes and that's also the ci-framework default.

Could we default preProvisioned to true? and have the kustomization switch it to false if it's set to false in the values.yaml?

 Similarly, could `baremetalSetTemplate` be added by kustomize when applicable?

@abays please let me know if I'm overlooking something.

**Comment by Jaganathancse** [comment]
> I've done all my testing with preprovisioned EDPM nodes and that's also the ci-framework default.
> 
> Could we default preProvisioned to true? and have the kustomization switch it to false if it's set to false in the values.yaml?
done
> 
> Similarly, could `baremetalSetTemplate` be added by kustomize when applicable?
> 
done
> @abays please let me know if I'm overlooking something.

Thanks @fultonj for comments. Please review the updated changes.

**Review by fultonj — APPROVED** [review]
Thanks @Jaganathancse 

@abays are you OK with this?

**Comment by abays** [comment]
I think it would be better to continue to use the `values*.yaml` pattern than introduce a new pattern where the user has to modify `kustomization.yaml`.  Could we move the fields marked `# CHANGEME` into the `values.yaml` and change the `patches` into `replacements` to retain the established pattern?

**Comment by abays** [comment]
> I think it would be better to continue to use the `values*.yaml` pattern than introduce a new pattern where the user has to modify `kustomization.yaml`. Could we move the fields marked `# CHANGEME` into the `values.yaml` and change the `patches` into `replacements` to retain the established pattern?

i.e. add the `preProvisioned` field and value along with the `baremetalSetTemplate` field and value to the respective `values.yaml` and then do something like [1], except make those changes in `examples/va/nfv/.../edpm/kustomization.yaml` instead of `va/nfv/.../edpm/kustomization.yaml`.

[1] https://github.com/openstack-k8s-operators/architecture/blob/6af47de32df784a87885d0a0f38bbe91c2abbab6/va/nfv/sriov/edpm/kustomization.yaml#L25-L51

**Comment by Jaganathancse** [comment]
> > I think it would be better to continue to use the `values*.yaml` pattern than introduce a new pattern where the user has to modify `kustomization.yaml`. Could we move the fields marked `# CHANGEME` into the `values.yaml` and change the `patches` into `replacements` to retain the established pattern?
> 
> i.e. add the `preProvisioned` field and value along with the `baremetalSetTemplate` field and value to the respective `values.yaml` and then do something like [1], except make those changes in `examples/va/nfv/.../edpm/kustomization.yaml` instead of `va/nfv/.../edpm/kustomization.yaml`.
> 
> [1]
> 
> https://github.com/openstack-k8s-operators/architecture/blob/6af47de32df784a87885d0a0f38bbe91c2abbab6/va/nfv/sriov/edpm/kustomization.yaml#L25-L51

done

**Pull request merged**
