### PR TITLE
Adding mkdocs

### PR DESCRIPTION
**Pull request by fao89**
Turning READMEs into docs:
image
image

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by fao89** [comment]
@abays could you please enable the deploy from branch?
https://github.com/openstack-k8s-operators/architecture/settings/pages
image

**Comment by abays** [comment]
> @abays could you please enable the deploy from branch? https://github.com/openstack-k8s-operators/architecture/settings/pages image

Done :+1:

**Comment by fao89** [comment]
Thank you @abays !
It is working: https://openstack-k8s-operators.github.io/architecture/

**Pull request merged**
