### PR TITLE
Add automation file for uni-alpha-adoption.

### PR DESCRIPTION
**Pull request by jparoly**
Runs only the first two stages of uni-alpha automation.

We would like to have this and the corresponding change merged.  Please see the Depends-On for more detail.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2555

### CODE REVIEW

**Comment by jparoly** [comment]
recheck

**Comment by fultonj** [comment]
I'm just labeling as do not merge for now since we're waiting on a review from jistr

**Review by ciecierski — APPROVED** [review]
lgtm

**Pull request merged**
