### PR TITLE
Revert "Revert Staticize dhcp config for eth0"

### PR DESCRIPTION
**Pull request by rabi**
Reverts openstack-k8s-operators/architecture#179

Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/624

### CODE REVIEW

**Review by abays — APPROVED** [review]
https://github.com/openstack-k8s-operators/edpm-ansible/pull/624 was merged

/lgtm

**Comment by rabi** [comment]
This works as tested in https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/5a73c2b8b3534ab9a9f33dbd34a1832f

But, we have to wait till the ansible-runner image is used in openstack-operator images.

**Pull request merged**
