### PR TITLE
Add worker node to run test operator on uni04delta-ipv6 deployments

### PR DESCRIPTION
**Pull request by gmarcian**
In order to run disruptive tests on the uni04delta env, We need to have a worker node dedicated for the test operator. 
Thus we can ensure that test pods won't be affected by the failures.
* Running disruptive tests is part of HA testing of the system. Please see [OSPRH-7602](https://issues.redhat.com/browse/OSPRH-7602)

### CODE REVIEW

**Comment by fultonj** [comment]
```
Sunday 22 September 2024  16:39:33 -0400 (0:00:00.050)       0:00:29.477 ****** 
fatal: [localhost]: FAILED! => changed=true 
  cmd:
  - oc
  - kustomize
  delta: '0:00:00.395164'
  end: '2024-09-22 16:39:34.530784'
  msg: non-zero return code
  rc: 1
  start: '2024-09-22 16:39:34.135620'
  stderr: 'error: fieldPath `data.node_3.internalapi_ip` is missing for replacement source ConfigMap.[noVer].[noGrp]/network-values.[noNs]'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
https://softwarefactory-project.io/zuul/t/rdoproject.org/build/26179debe63644d6bff1fc3873e5d9dd

**Comment by gmarcian** [comment]
Tested upstream: https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/4702eb82b51945868ad8bbbbbd107dd8/logs

**Comment by fultonj** [comment]
> https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/4702eb82b51945868ad8bbbbbd107dd8/logs

I see that test failed. Shouldn't it pass before we merge it?

**Comment by fultonj** [comment]
So all uni04delta-ipv6 deployments will be able to run with four OCP nodes; i.e. 3 masters and 1 new worker node introduced by this patch? 

I see it's following the pattern used here:

  https://github.com/openstack-k8s-operators/architecture/commit/426b290a91f09c429d9389d411b4ef0c2f3e6b59

@arxcruz I'm assuming our testing nodes have the resources to handle the exta node.

@tosky I'm assuming this won't cause problems for storage related tests in this DT.

I'm OK with it provided we have the resources to handle it and others who depend on  uni04delta-ipv6 are OK with it.

**Comment by abays** [comment]
> > https://sf.hosted.upshift.rdu2.redhat.com/zuul/t/tripleo-ci-internal/build/4702eb82b51945868ad8bbbbbd107dd8/logs
> 
> I see that test failed. Shouldn't it pass before we merge it?

I also echo John's question.

**Comment by gmarcian** [comment]
So, it seems to be ready now.
A testproject job[1] passed the deployment;
Two Tempest tests failed here[2] - they also were failing on the official uni04delta-ipv6 [3].
Tobiko ipv4/ipv6 connectivity issue was resolved in [4] 
Remaining failed tests are related to [5] - need to be fixed in tobiko framework.
[1] https://gitlab.cee.redhat.com/ci-framework/ci-framework-testproject/-/merge_requests/698
[2] https://sf.hosted.upshift.rdu2.redhat.com/logs/98/698/25ca684db05f6156f2e656a99a1b273d47e63621/check-gitlab-cee/uni04delta-ipv6-rhel9-rhoso18.0-pidone-titan151/17f6a07/logs/controller-0/ci-framework-data/tests/test_operator/tempest-tests-multi-thread-testing-workflow-step-0/stestr_results.html

[3] https://sf.hosted.upshift.rdu2.redhat.com/logs/openstack-uni-update-jobs-periodic-integration-rhoso18.0-rhel9/gitlab.cee.redhat.com/ci-framework/ci-framework-jobs/main/uni04delta-ipv6-rhel9-rhoso18.0-update/2dc3eed/logs/controller-0/ci-framework-data/tests/test_operator/post-deployment-tempest-multi-thread-testing-workflow-step-0/stestr_results.html

[4] https://gitlab.cee.redhat.com/ci-framework/ci-framework-jobs/-/merge_requests/1187
[5] https://issues.redhat.com/browse/TOBIKO-126

**Review by abays — COMMENTED** [review]
Given @gmarcian's recent update, I am good with this.  But I will defer to @fultonj to have the final word for approval.

/lgtm

**Comment by tosky** [comment]
Please please next time squash all the changes, otherwise the git history becomes complicated to follow. This is a request to the reviewers too.

**Comment by abays** [comment]
> Please please next time squash all the changes, otherwise the git history becomes complicated to follow. This is a request to the reviewers too.

Do you mean have Zuul squash everything when it merges, or ask the author to squash their commits?

**Comment by tosky** [comment]
> > Please please next time squash all the changes, otherwise the git history becomes complicated to follow. This is a request to the reviewers too.
> 
> Do you mean have Zuul squash everything when it merges, or ask the author to squash their commits?

I would be more for "have the author present a clean history", as there may be cases where the original commits need to be preserved. But that's up to you.

**Comment by gmarcian** [comment]
@tosky  Ack. Can it be done from the github PR GUI?

**Comment by tosky** [comment]
> @tosky Ack. Can it be done from the github PR GUI?

I'll leave the answer to others who know the github GUI, but I would say: no. Better rebase locally, you have more control (the operation is a local rebase of the history): https://about.gitlab.com/blog/2020/11/23/keep-git-history-clean-with-interactive-rebase/ (yes, the article is from gitlab.com, but it describes the step to execute with the git CLI tool).

**Pull request merged**
