### PR TITLE
Security DFG DT commit

### PR DESCRIPTION
**Pull request by jagee**

### CODE REVIEW

**Comment by tosky** [comment]
My question is: do all of these need to be DTs? Can't those be run at the component level? Especially the ones which use specific backends. It is true they may need a few more components, but generally speaking if you enable image signature you will be just able to run a limited amount of tests, which makes it suitable for running at that part of the pipeline.

**Comment by millevy** [comment]
> My question is: do all of these need to be DTs? Can't those be run at the component level? Especially the ones which use specific backends. It is true they may need a few more components, but generally speaking if you enable image signature you will be just able to run a limited amount of tests, which makes it suitable for running at that part of the pipeline.

Hi, actually we do need to get most of it deleted and move to Jiras. I was trying to figure out how to. I will move it now to Jiras and I will ask Jeremy to change his PR.

**Review by millevy — CHANGES_REQUESTED** [review]
This DT belong to the component ci and need to be removed.

**Review by millevy — CHANGES_REQUESTED** [review]
Please remove all the DTs that belong to the Component CI

**Pull request closed without merging**
