### PR TITLE
Start adding validation jobs

### PR DESCRIPTION
**Pull request by cjeanner**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1728

### CODE REVIEW

**Comment by cjeanner** [comment]
NFV job would require some mock files to provide dummy data - this isn't supported yet, buuut... we're here to improve!

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
at least, depends-on works as expected :champagne:

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
@abays @fultonj depends-on patch is merged, we can start getting CI!

**Review by fultonj — APPROVED** [review]
+2

I think of this like an alternative implementation of test-kustomizations.sh in ansible which uses the ci-framework calls that build the CRs. It covers what test-kustomizations.sh does and more.

**Comment by fultonj** [comment]
After discussing w/ Leif and Andrew we're all happy to have this patch. Thanks Cedric.

**Pull request merged**
