### PR TITLE
Add a global flag to enable preserveJobs in all svcs

### PR DESCRIPTION
**Pull request by pablintino**

### CODE REVIEW

**Review by gibizer — COMMENTED** [review]
looks OK to me.

**Review by hjensas — COMMENTED** [review]
Looks good to me.

**Comment by pablintino** [comment]
As soon as the unrelated CI issues we are facing because of EDPM not able to finish the deployment I'll test this.

**Review by fultonj — COMMENTED** [review]
This PR looks fine to me. It sufficiently sets `preserveJobs: false`. Let's confirm via testing it's OK to merge first though.

**Comment by fultonj** [comment]
@rlandy has confirmed  that this has been tested

**Comment by fultonj** [comment]
It's not passing [test-kustomize](https://github.com/openstack-k8s-operators/architecture/actions/runs/9522195954/job/26251235404?pr=281)
```
examples/dt/uni07eta/control-plane/kustomization.yaml: ERROR
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/home/runner/work/architecture/architecture/dt/uni07eta': accumulating components: accumulateDirectory: \"recursed accumulation of path '/home/runner/work/architecture/architecture/lib/control-plane': fieldPath `data.preserveJobs` is missing for replacement source ConfigMap.[noVer].[noGrp]/service-values.[noNs]\""
```

**Comment by fultonj** [comment]
I've confirmed that the main branch does not have the `recursed accumulation of path '/home/fultonj/git/openstack-k8s-operators/architecture/dt/uni07eta` but that this patch (PR 281) does.

**Comment by fultonj** [comment]
You just need to update this patch to include a change to `examples/dt/uni07eta/control-plane/service-values.yaml`.

```
[fultonj@runcible architecture{preserve-jobs-global-flag}]$ git status
On branch preserve-jobs-global-flag
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   examples/dt/uni07eta/control-plane/service-values.yaml

no changes added to commit (use "git add" and/or "git commit -a")
[fultonj@runcible architecture{preserve-jobs-global-flag}]$ git diff
diff --git a/examples/dt/uni07eta/control-plane/service-values.yaml b/examples/dt/uni07eta/control-plane/service-values.yaml
index 722549f..f607f42 100644
--- a/examples/dt/uni07eta/control-plane/service-values.yaml
+++ b/examples/dt/uni07eta/control-plane/service-values.yaml
@@ -8,6 +8,7 @@ metadata:
     config.kubernetes.io/local-config: "true"
 
 data:
+  preserveJobs: false
   cinderVolumes:
     ontap-iscsi:
       customServiceConfig: |
[fultonj@runcible architecture{preserve-jobs-global-flag}]$ 
```

**Review by fultonj — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
