### PR TITLE
Initial commit - NetApp DT job definition

### PR DESCRIPTION
**Pull request by vhariria**
This PR is the preliminary job definition based on guidelines shared with QE and includes component customization based on 17.1 unified NetApp jobs.

### CODE REVIEW

**Comment by tosky** [comment]
For the record, the configuration is mostly a copy of the template, and I'm going to submit a full version of this job. Please hold on.

**Comment by vhariria** [comment]
This PR is the preliminary definition based on guideline share earlier with QE and  includes component customization based on 17.1 unified NetApp jobs.

**Comment by vhariria** [comment]
> For the record, the configuration is mostly a copy of the template, and I'm going to submit a full version of this job. Please hold on.

Correction. This PR is based on the collaborative DT job description for Manila with cephfs backends.  The content has since been approved for further enhancements.

**Comment by tosky** [comment]
The file i

> > For the record, the configuration is mostly a copy of the template, and I'm going to submit a full version of this job. Please hold on.
> 
> Please note that, this PR is based on the collaborative DT job description for Manila with cephfs backends. The content has since been approved for further enhancements.

The PR simply changes the Manila line in the example DT. It doesn't change the rest of the configuration, doesn't even specify to run manila tests and it would require a lot of changes.

I suggest closing this and referring to https://github.com/openstack-k8s-operators/architecture/pull/45 instead.

**Comment by vhariria** [comment]
Verified that a basic NetApp topology is included in https://github.com/openstack-k8s-operators/architecture/pull/45.

**Pull request closed without merging**
