### PR TITLE
[va-hci] Remove references to edpm images

### PR DESCRIPTION
**Pull request by eduolivares**
Default image versions obtained from the dataplane-operator will be used instead

### CODE REVIEW

**Review by abays — APPROVED** [review]
Tested with VA1.  Deployment succeeded and Tempest passed.

/lgtm

**Comment by karelyatin** [comment]
/lgtm

The defaults for edpm images is managed in [dataplane-operator](https://github.com/openstack-k8s-operators/dataplane-operator/blob/4c739fb27266a1e70d92fe73184cd1ef2e7b2132/pkg/deployment/inventory.go#L239-L240), overriding just the edpm images and not the control plane(specifically OVN images atleast) can cause issues as mentioned in https://issues.redhat.com/browse/OSPRH-1504 . The new way for managing the both control plane/data plane is with OpenStackVersion CR.

@eduolivares please drop WIP from commit

**Comment by eduolivares** [comment]
> /lgtm
> 
> The defaults for edpm images is managed in [dataplane-operator](https://github.com/openstack-k8s-operators/dataplane-operator/blob/4c739fb27266a1e70d92fe73184cd1ef2e7b2132/pkg/deployment/inventory.go#L239-L240), overriding just the edpm images and not the control plane(specifically OVN images atleast) can cause issues as mentioned in https://issues.redhat.com/browse/OSPRH-1504 . The new way for managing the both control plane/data plane is with OpenStackVersion CR.
> 
> @eduolivares please drop WIP from commit

WIP removed from both commit and PR messages.

**Comment by abays** [comment]
Please wait to merge this until after https://github.com/openstack-k8s-operators/architecture/pull/197 is merged, and then kindly rebase.  We're splitting the EDPM deployment and the file modified in this PR will no longer exist under the current path.

**Review by abays — APPROVED** [review]
/lgtm

**Comment by leifmadsen** [comment]
Just throwing needs-info on this to make sure there is no issue across other VAs or DTs as they should all remain in sync.

**Comment by eduolivares** [comment]
> Just throwing needs-info on this to make sure there is no issue across other VAs or DTs as they should all remain in sync.

It seems no other VAs/DTs specify the EDPM images used:
```
architecture (main) $ git grep "edpm_.*_image"
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_iscsid_image: '{{ registry_url }}/openstack-iscsid:{{ image_tag }}'
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_logrotate_crond_image: '{{ registry_url }}/openstack-cron:{{ image_tag }}'
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_neutron_metadata_agent_image: '{{ registry_url }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}'
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_nova_compute_container_image: '{{ registry_url }}/openstack-nova-compute:{{ image_tag }}'
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_nova_libvirt_container_image: '{{ registry_url }}/openstack-nova-libvirt:{{ image_tag }}'
examples/va/hci/edpm-pre-ceph/nodeset/values.yaml:        edpm_ovn_controller_agent_image: '{{ registry_url }}/openstack-ovn-controller:{{ image_tag }}'
```

I am working on a PR where EDPM images were specified too, but I removed them yesterday:
https://github.com/openstack-k8s-operators/architecture/pull/193#event-12639655257

So, I think all VAs and DTs are synchronized.

**Review by leifmadsen — APPROVED** [review]

**Pull request merged**
