### PR TITLE
Use uni* specific Net Env Def in CI

### PR DESCRIPTION
**Pull request by pablintino**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1816

### CODE REVIEW

**Comment by psathyan** [comment]
IMHO, we wouldn't need these changes as the master mock file data contains all the required information.

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by fultonj** [comment]
@pablintino @rebtoor I'm waiting for you to confirm this is tested before merging.

**Comment by rebtoor** [comment]
> @pablintino @rebtoor I'm waiting for you to confirm this is tested before merging.

Isn't ready yet. I'm still having issues with pidone scenario. I'll let you know when it will be ready to merge.

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
@fultonj @pablintino now is ready now. Every scenario has been tested and it's working.

Be aware that `file-consistency/test-zuul` job is broken due to the introduction of `net-env` files, so if we merge this PR before have fixed that job (i'm taking care of it), we need to carefully analyze the content of the `zuul.d/validations.yaml` file in other PRs.

**Comment by fultonj** [comment]
waiting for the following to merge 

https://github.com/openstack-k8s-operators/ci-framework/pull/1816

**Review by fultonj — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
