### PR TITLE
Move bgp_dt01 into its own automation file

### PR DESCRIPTION
**Pull request by raukadah**
openstack-k8s-operators/architecture#375 splits the default vars into different scenario files. We need to follow similar pattern for bgp_dt01 also.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2267

### CODE REVIEW

**Comment by cjeanner** [comment]
/lgtm

This PR has been integrated in my linter one (#379 ) and it's green now.

**Comment by cjeanner** [comment]
(Note: it might require a sync with the bgp team - need to ping them)

**Comment by cjeanner** [comment]
/hold

some tests are done - let's hold it.

**Comment by fultonj** [comment]
I'm +2 on this in theory. Holding per Cedric's comments.

**Review by marios — APPROVED** [review]

**Comment by marios** [comment]
didn't expect this to merge with just one approval @raukadah @cjeanner was there something further here?
it looks like the labels didn't work as intended ? (do not merge)

**Comment by eduolivares** [comment]
removing the label because porting to 18.0.0-proposed doesn't seem to be necessary

**Pull request merged**
